[CmdletBinding()]
param(
    [string]$Version = "0.1.0"
)

$ErrorActionPreference = 'Stop'
$Runtime = "win-x64"

# Paths (script lives in <repo>/scripts)
$RepoRoot  = Split-Path -Parent $PSScriptRoot
$Backend   = Join-Path $RepoRoot  "claude-orchestrator-web\backend"
$Csproj    = Join-Path $Backend   "ClaudeOrchestrator.csproj"
$PtyProxy  = Join-Path $Backend   "pty-proxy"
$AssetsDir = Join-Path $PSScriptRoot "dist-assets"
$DistDir   = Join-Path $RepoRoot  "dist"
$StageName = "ClaudeAgentOrchestrator-$Runtime-$Version"
$Staging   = Join-Path $DistDir   $StageName
$ZipPath   = Join-Path $DistDir   "$StageName.zip"

Write-Host "==> Cleaning previous dist output"
if (Test-Path $DistDir) { Remove-Item $DistDir -Recurse -Force }
New-Item -ItemType Directory -Path $DistDir | Out-Null

# Hard-clean the backend build output. `dotnet clean` alone does NOT reliably
# purge the StaticWebAssets manifests in obj/, which pin the *previous* Vite
# asset hashes. Vite regenerates hashes on every build, so a stale manifest
# makes publish try to copy asset filenames that no longer exist (MSB3030).
# Deleting obj/bin/wwwroot (all git-ignored, regenerated by the publish) forces
# a fresh, self-consistent frontend build + manifest.
Write-Host "==> Hard-cleaning backend obj/bin/wwwroot"
foreach ($d in @(
    (Join-Path $Backend "obj"),
    (Join-Path $Backend "bin"),
    (Join-Path $Backend "wwwroot")
)) {
    if (Test-Path $d) { Remove-Item $d -Recurse -Force }
}

Write-Host "==> Installing pty-proxy dependencies (npm ci)"
Push-Location $PtyProxy
try {
    npm ci
    if ($LASTEXITCODE -ne 0) { throw "npm ci (pty-proxy) failed ($LASTEXITCODE)" }
} finally { Pop-Location }

Write-Host "==> Publishing self-contained $Runtime"
dotnet publish $Csproj -c Release -r $Runtime --self-contained `
    -p:EnableDefaultCompressedItems=false `
    -o $Staging
if ($LASTEXITCODE -ne 0) { throw "dotnet publish failed ($LASTEXITCODE)" }

Write-Host "==> Adding launcher and guide"
Copy-Item (Join-Path $AssetsDir "Spustit.bat")   $Staging
Copy-Item (Join-Path $AssetsDir "START-HERE.txt") $Staging

Write-Host "==> Creating zip"
if (Test-Path $ZipPath) { Remove-Item $ZipPath -Force }
Add-Type -AssemblyName System.IO.Compression.FileSystem
# ZipFile::CreateFromDirectory is far faster and more reliable than
# Compress-Archive on large trees (the self-contained publish is ~170 MB;
# Compress-Archive on Windows PowerShell 5.1 stalls on it). The 4th arg
# includeBaseDirectory=$true keeps the top-level folder inside the zip.
[System.IO.Compression.ZipFile]::CreateFromDirectory(
    $Staging, $ZipPath,
    [System.IO.Compression.CompressionLevel]::Optimal, $true)

Write-Host ""
Write-Host "==> Done: $ZipPath"
Write-Host "    Size: $([math]::Round((Get-Item $ZipPath).Length / 1MB, 1)) MB"
